# Generated by Django 5.2.9 on 2026-01-09 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='override_enabled',
            field=models.BooleanField(default=False, help_text='If TRUE, toolbar_override is applied; if FALSE, uses ERPMenuItem.toolbar_config'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='toolbar_override',
            field=models.CharField(blank=True, help_text='15-button override: N,E,S,C,L,T,A,V,P,R,D,X,Y,Z,O. If NULL, inherits from ERPMenuItem.toolbar_config', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_role_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='toolbar_override',
            field=models.CharField(blank=True, help_text='User-specific 15-button override. If NULL, inherits from Role or ERPMenuItem', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ERPMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('menu_name', models.CharField(max_length=200)),
                ('module_name', models.CharField(choices=[('RETAIL', 'Retail Operations'), ('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management')], max_length=50)),
                ('submodule', models.CharField(blank=True, help_text='e.g., INVENTORY, SALES, PROCUREMENT', max_length=50, null=True)),
                ('view_type', models.CharField(choices=[('MASTER', 'Master Data'), ('TRANSACTION', 'Transaction'), ('REPORT', 'Report'), ('DASHBOARD', 'Dashboard'), ('LIST', 'List View')], default='LIST', max_length=20)),
                ('toolbar_config', models.CharField(default='1,1,1,1,1,1,1,1,1,1,1,1,1,1,1', help_text='15-button config: N,E,S,C,L,T,A,V,P,R,D,X,Y,Z,O (1=enabled, 0=disabled)', max_length=50)),
                ('toolbar_config_backup', models.CharField(blank=True, help_text='Backup config for license restoration', max_length=50, null=True)),
                ('is_license_controlled', models.BooleanField(default=True, help_text='If True, toolbar is disabled when license expires')),
                ('route_path', models.CharField(blank=True, help_text='Frontend route path', max_length=200, null=True)),
                ('component_name', models.CharField(blank=True, help_text='React component name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_menu', models.BooleanField(default=False, help_text='System menus cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menu_items', to=settings.AUTH_USER_MODEL)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user_management.erpmenuitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_menu_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP Menu Item',
                'verbose_name_plural': 'ERP Menu Items',
                'db_table': 'erp_menu_items',
                'ordering': ['module_name', 'submodule', 'menu_order', 'menu_name'],
            },
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='user_management.erpmenuitem'),
        ),
        migrations.AlterField(
            model_name='permissionaudit',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.erpmenuitem'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='user_management.erpmenuitem'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='user_management.erpmenuitem'),
        ),
        migrations.DeleteModel(
            name='MenuItemType',
        ),
    ]
