# Generated by Django 5.2.9 on 2026-01-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_rolepermission_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPToolbarControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('RETAIL', 'Retail Operations'), ('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management')], max_length=50, unique=True)),
                ('master_toolbar_string', models.CharField(help_text="Master string of all permitted action codes (e.g., 'NESCAZ...')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ERP Toolbar Control',
                'verbose_name_plural': 'ERP Toolbar Controls',
                'db_table': 'erp_toolbar_controls',
            },
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='applicable_toolbar_config',
            field=models.CharField(blank=True, help_text="Effective toolbar string for this specific menu item (e.g. 'NESC')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='original_toolbar_string',
            field=models.CharField(blank=True, help_text='DerivedSuperset from ERPToolbarControl (Read Only logic)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='erpmenuitem',
            name='toolbar_config',
            field=models.CharField(default='1,1,1,1,1,1,1,1,1,1,1,1,1,1,1', help_text='[DEPRECATED] 15-button config', max_length=50),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='toolbar_override',
            field=models.CharField(blank=True, help_text='String override (e.g. "NESC"). If NULL, inherits from ERPMenuItem.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='toolbar_override',
            field=models.CharField(blank=True, help_text='User-specific string override. If NULL, inherits from Role or ERPMenuItem', max_length=100, null=True),
        ),
    ]




