# Generated by Django 5.2.9 on 2026-01-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_erptoolbarcontrol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'User Permission', 'verbose_name_plural': 'User Permissions'},
        ),
    ]




