# Generated by Django 5.2.9 on 2026-01-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userpermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmenuitem',
            name='module_name',
            field=models.CharField(choices=[('RETAIL', 'Retail Operations'), ('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management'), ('ADMIN', 'Administration'), ('SETUP', 'System Setup'), ('SYSTEM', 'System Infrastructure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='erpmenuitem',
            name='view_type',
            field=models.CharField(choices=[('MASTER', 'Master Data'), ('TRANSACTION', 'Transaction'), ('REPORT', 'Report'), ('DASHBOARD', 'Dashboard'), ('LIST', 'List View'), ('CONFIGURATION', 'Configuration/Settings')], default='LIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='erptoolbarcontrol',
            name='module_name',
            field=models.CharField(choices=[('RETAIL', 'Retail Operations'), ('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management'), ('ADMIN', 'Administration'), ('SETUP', 'System Setup'), ('SYSTEM', 'System Infrastructure')], max_length=50, unique=True),
        ),
    ]




