# Generated by Django 5.2.9 on 2026-01-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_erpmenuitem_module_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='toolbar_permissions',
            field=models.CharField(blank=True, help_text='Permission mask: 1=allowed, 0=denied (e.g., "110111010011011110011"). Each position maps to toolbar_string character.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='toolbar_string',
            field=models.CharField(blank=True, help_text='Toolbar capability string from ERPMenuItem (e.g., "NESCKZTJAVPMRDX1234QF")', max_length=100, null=True),
        ),
    ]




