# Generated by Django 5.2.9 on 2026-01-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_add_toolbar_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmenuitem',
            name='view_type',
            field=models.CharField(choices=[('MASTER', 'Master Data'), ('TRANSACTION', 'Transaction'), ('REPORT', 'Report'), ('DASHBOARD', 'Dashboard'), ('CONFIGURATION', 'Configuration/Settings')], default='TRANSACTION', max_length=20),
        ),
    ]
