# Generated by Django 5.1.2 on 2026-01-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_erpmenuitem_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_create',
            field=models.CharField(blank=True, help_text="Toolbar configuration for CREATE mode (e.g. 'SCX')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_edit',
            field=models.CharField(blank=True, help_text="Toolbar configuration for EDIT mode (e.g. 'SCX')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_list',
            field=models.CharField(blank=True, help_text="Toolbar configuration for LIST mode (e.g. 'NRQFVIOX')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_view',
            field=models.CharField(blank=True, help_text="Toolbar configuration for VIEW mode (e.g. 'X')", max_length=100, null=True),
        ),
    ]
