# Generated by Django 5.1.2 on 2026-01-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_erpmenuitem_toolbar_create_erpmenuitem_toolbar_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpmenuitem',
            name='toolbar_create',
        ),
        migrations.RemoveField(
            model_name='erpmenuitem',
            name='toolbar_edit',
        ),
        migrations.RemoveField(
            model_name='erpmenuitem',
            name='toolbar_list',
        ),
        migrations.RemoveField(
            model_name='erpmenuitem',
            name='toolbar_view',
        ),
        migrations.DeleteModel(
            name='UserLocationMapping',
        ),
    ]
