# Generated by Django 5.1.2 on 2026-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_remove_erpmenuitem_toolbar_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_create',
            field=models.CharField(blank=True, help_text="Toolbar config for CREATE mode (e.g., 'SCX')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_edit',
            field=models.CharField(blank=True, help_text="Toolbar config for EDIT mode (e.g., 'SCX')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_list',
            field=models.CharField(blank=True, help_text="Toolbar config for LIST mode (e.g., 'NRQFVIOX')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_view',
            field=models.CharField(blank=True, help_text="Toolbar config for VIEW mode (e.g., 'X')", max_length=100, null=True),
        ),
    ]
