# Generated by Django 5.2.9 on 2025-12-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='Unique license identifier', max_length=255, unique=True)),
                ('licensee_name', models.CharField(help_text='Organization name', max_length=255)),
                ('max_companies', models.PositiveIntegerField(default=1, help_text='Maximum number of Companies that can be created')),
                ('max_locations_per_company', models.PositiveIntegerField(default=5, help_text='Maximum number of Locations per Company')),
                ('max_total_locations', models.PositiveIntegerField(default=10, help_text='Maximum total Locations across all Companies')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for perpetual', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License Configuration',
                'verbose_name_plural': 'License Configurations',
                'db_table': 'licensing_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicensedEntity',
            fields=[
            ],
            options={
                'verbose_name': 'Business Entity',
                'verbose_name_plural': 'Business Entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('business_entities.company',),
        ),
    ]




