# Generated by Django 5.2.9 on 2026-01-02 15:11
# MODIFIED: Removed retail_domain dependency for HRM-only setup
# The Location model has been removed from this app (Retail-only)
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_alter_itemvariant_item'),
        # Removed ('retail_domain', '__first__') dependency - Retail-only app not available
    ]

    operations = [
        # Remove location_scope field from PriceListLine (Location is Retail-only)
        migrations.RemoveField(
            model_name='pricelistline',
            name='location_scope',
        ),
    ]
