# Generated by Django 5.1.2 on 2026-01-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_location_company_and_more'),
        ('user_management', '0010_remove_erpmenuitem_toolbar_create_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
