# Generated by Django 5.2.9 on 2026-01-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ERPToolbarControl',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='ERPMenuItem',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
