# Generated by Django 5.1.2 on 2026-01-21 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_remove_rolepermission_menu_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('View', 'View'), ('Download', 'Download'), ('Print', 'Print'), ('Share', 'Share'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='View', max_length=20)),
                ('permission_level', models.CharField(choices=[('Owner', 'Owner'), ('Full Access', 'Full Access'), ('Read Only', 'Read Only'), ('Restricted', 'Restricted')], default='Read Only', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_restriction', models.CharField(blank=True, max_length=45, null=True)),
                ('time_restriction', models.JSONField(default=dict, help_text='Allowed time windows')),
                ('download_limit', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Access Control',
                'verbose_name_plural': 'Document Access Controls',
                'db_table': 'document_access_control',
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('action', models.CharField(choices=[('Upload', 'Upload'), ('View', 'View'), ('Download', 'Download'), ('Print', 'Print'), ('Share', 'Share'), ('Delete', 'Delete'), ('Verify', 'Verify'), ('Archive', 'Archive')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile'), ('Tablet', 'Tablet')], max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('success_flag', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('additional_context', models.JSONField(default=dict, help_text='Extra context information')),
            ],
            options={
                'verbose_name': 'Document Analytics',
                'verbose_name_plural': 'Document Analytics',
                'db_table': 'document_analytics',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('type_code', models.CharField(db_index=True, max_length=50)),
                ('type_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Employment', 'Employment'), ('Education', 'Education'), ('Professional', 'Professional'), ('Legal', 'Legal'), ('Medical', 'Medical'), ('Financial', 'Financial'), ('Training', 'Training'), ('Performance', 'Performance'), ('Compliance', 'Compliance')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_mandatory_for_onboarding', models.BooleanField(default=False)),
                ('is_mandatory_for_exit', models.BooleanField(default=False)),
                ('requires_verification', models.BooleanField(default=True)),
                ('expiry_required', models.BooleanField(default=False)),
                ('expiry_days', models.IntegerField(default=365)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('allowed_file_types', models.JSONField(default=list, help_text='Array of allowed file extensions')),
                ('access_level', models.CharField(choices=[('Public', 'Public'), ('HR Only', 'HR Only'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Restricted', 'Restricted')], default='HR Only', max_length=20)),
                ('retention_years', models.IntegerField(default=7)),
                ('auto_archive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type Master',
                'verbose_name_plural': 'Document Type Masters',
                'db_table': 'document_type_master',
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('Manual', 'Manual'), ('Automated', 'Automated'), ('Third Party', 'Third Party'), ('E-Signature', 'E-Signature')], default='Manual', max_length=20)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Requires Additional Info', 'Requires Additional Info')], default='Pending', max_length=30)),
                ('verification_method', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_result', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verification_score', models.IntegerField(blank=True, help_text='0-100', null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('next_verification_date', models.DateField(blank=True, null=True)),
                ('supporting_documents', models.JSONField(default=list, help_text='Array of supporting document IDs')),
                ('verification_checklist', models.JSONField(default=dict, help_text='Checklist items and results')),
                ('automated_checks', models.JSONField(default=dict, help_text='Automated validation results')),
                ('third_party_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'db_table': 'document_verification',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(help_text='SHA-256 hash', max_length=256)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Superseded', 'Superseded'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'db_table': 'document_version',
            },
        ),
        migrations.RemoveIndex(
            model_name='employeedocument',
            name='idx_doc_employee',
        ),
        migrations.RemoveIndex(
            model_name='employeedocument',
            name='idx_app_doc_type_emp',
        ),
        migrations.RemoveIndex(
            model_name='employeedocument',
            name='idx_doc_active',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='is_confidential',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='backup_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Document metadata'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Uploaded', 'Uploaded'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Archived', 'Archived')], default='Uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='storage_location',
            field=models.CharField(choices=[('Local', 'Local'), ('Cloud', 'Cloud'), ('Hybrid', 'Hybrid')], default='Local', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='tags',
            field=models.JSONField(default=list, help_text='Array of tags'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.employeerecord'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='documentaccesscontrol',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='hrm.employeedocument'),
        ),
        migrations.AddField(
            model_name='documentaccesscontrol',
            name='granted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccesscontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentanalytics',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='hrm.employeedocument'),
        ),
        migrations.AddField(
            model_name='documentanalytics',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analytics', to='hrm.employeerecord'),
        ),
        migrations.AddField(
            model_name='documentanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttypemaster',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctype_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hrm.documenttypemaster'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='idx_doc_employee_type'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['document_name'], name='idx_doc_name'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['status'], name='idx_doc_status'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['upload_date'], name='idx_doc_upload_date'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['expiry_date'], name='idx_doc_expiry_date'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['is_current'], name='idx_doc_current'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['file_hash'], name='idx_doc_hash'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['uploaded_by_user'], name='idx_doc_uploader'),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='hrm.employeedocument'),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_versions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hrm.employeedocument'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_versions_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentaccesscontrol',
            index=models.Index(fields=['document', 'user'], name='idx_access_doc_user'),
        ),
        migrations.AddIndex(
            model_name='documentaccesscontrol',
            index=models.Index(fields=['access_type'], name='idx_access_type'),
        ),
        migrations.AddIndex(
            model_name='documentaccesscontrol',
            index=models.Index(fields=['permission_level'], name='idx_access_permission'),
        ),
        migrations.AddIndex(
            model_name='documentaccesscontrol',
            index=models.Index(fields=['granted_by_user'], name='idx_access_granter'),
        ),
        migrations.AddIndex(
            model_name='documentaccesscontrol',
            index=models.Index(fields=['expires_at'], name='idx_access_expires'),
        ),
        migrations.AddIndex(
            model_name='documentaccesscontrol',
            index=models.Index(fields=['is_active'], name='idx_access_active'),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccesscontrol',
            unique_together={('document', 'user', 'access_type')},
        ),
        migrations.AddIndex(
            model_name='documentanalytics',
            index=models.Index(fields=['company_code', 'document'], name='idx_analytics_company_doc'),
        ),
        migrations.AddIndex(
            model_name='documentanalytics',
            index=models.Index(fields=['employee', 'action'], name='idx_analytics_employee_action'),
        ),
        migrations.AddIndex(
            model_name='documentanalytics',
            index=models.Index(fields=['user', 'action_timestamp'], name='idx_analytics_user_time'),
        ),
        migrations.AddIndex(
            model_name='documentanalytics',
            index=models.Index(fields=['action', 'action_timestamp'], name='idx_analytics_action_time'),
        ),
        migrations.AddIndex(
            model_name='documentanalytics',
            index=models.Index(fields=['device_type'], name='idx_analytics_device'),
        ),
        migrations.AddIndex(
            model_name='documenttypemaster',
            index=models.Index(fields=['company_code', 'type_code'], name='idx_doctype_company_code'),
        ),
        migrations.AddIndex(
            model_name='documenttypemaster',
            index=models.Index(fields=['category'], name='idx_doctype_category'),
        ),
        migrations.AddIndex(
            model_name='documenttypemaster',
            index=models.Index(fields=['is_required'], name='idx_doctype_required'),
        ),
        migrations.AddIndex(
            model_name='documenttypemaster',
            index=models.Index(fields=['is_active'], name='idx_doctype_active'),
        ),
        migrations.AddIndex(
            model_name='documenttypemaster',
            index=models.Index(fields=['display_order'], name='idx_doctype_display_order'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttypemaster',
            unique_together={('company_code', 'type_code')},
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['document', 'verification_type'], name='idx_verify_doc_type'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['verifier'], name='idx_verify_verifier'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['verification_status'], name='idx_verify_status'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['verification_date'], name='idx_verify_date'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['expiry_date'], name='idx_verify_expiry'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_number'], name='idx_version_doc_number'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['status'], name='idx_version_status'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['effective_date'], name='idx_version_effective'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['uploaded_by_user'], name='idx_version_uploader'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['approved_by_user'], name='idx_version_approver'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
