# Generated by Django 5.1.2 on 2026-01-21 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_documentaccesscontrol_documentanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('Personal Info', 'Personal Info'), ('Contact Info', 'Contact Info'), ('Bank Details', 'Bank Details'), ('Emergency Contact', 'Emergency Contact'), ('Tax Info', 'Tax Info'), ('Address', 'Address')], db_index=True, max_length=50)),
                ('employee_category', models.CharField(choices=[('All', 'All'), ('Staff', 'Staff'), ('Worker', 'Worker'), ('Executive', 'Executive'), ('Management', 'Management')], db_index=True, default='All', max_length=20)),
                ('approval_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('approver_type', models.CharField(choices=[('Manager', 'Manager'), ('HR Admin', 'HR Admin'), ('Department Head', 'Department Head'), ('Specific User', 'Specific User')], db_index=True, max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_parallel', models.BooleanField(default=False)),
                ('time_limit_hours', models.IntegerField(default=48)),
                ('auto_approve', models.BooleanField(default=False)),
                ('conditions', models.JSONField(default=dict, help_text='Approval conditions')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_matrix_entries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_matrices', to='hrm.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_matrices', to='hrm.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_matrices', to='hrm.organizationalunit')),
            ],
            options={
                'verbose_name': 'Approval Matrix',
                'verbose_name_plural': 'Approval Matrices',
                'db_table': 'approval_matrix',
            },
        ),
        migrations.CreateModel(
            name='EmployeeChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('request_type', models.CharField(choices=[('Personal Info', 'Personal Info'), ('Contact Info', 'Contact Info'), ('Bank Details', 'Bank Details'), ('Emergency Contact', 'Emergency Contact'), ('Tax Info', 'Tax Info'), ('Address', 'Address')], db_index=True, max_length=50)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('change_reason', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], db_index=True, default='Draft', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], db_index=True, default='Medium', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='hrm.employeerecord')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_change_requests', to='hrm.employeedocument')),
            ],
            options={
                'verbose_name': 'Employee Change Request',
                'verbose_name_plural': 'Employee Change Requests',
                'db_table': 'employee_change_request',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delegated', 'Delegated'), ('Escalated', 'Escalated')], db_index=True, default='Pending', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Request More Info', 'Request More Info'), ('Delegate', 'Delegate')], db_index=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list, help_text='Array of document IDs')),
                ('due_date', models.DateTimeField(db_index=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('delegated_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL)),
                ('escalated_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='hrm.approvalmatrix')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='hrm.employeechangerequest')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'approval_workflow',
            },
        ),
        migrations.CreateModel(
            name='ESSAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Submit', 'Submit'), ('Approve', 'Approve'), ('Reject', 'Reject'), ('View', 'View'), ('Download', 'Download')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(choices=[('Change Request', 'Change Request'), ('Service Request', 'Service Request'), ('Personal Info', 'Personal Info'), ('Document', 'Document'), ('Approval Workflow', 'Approval Workflow')], db_index=True, max_length=20)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('old_values', models.JSONField(default=dict, help_text='Previous values')),
                ('new_values', models.JSONField(default=dict, help_text='Updated values')),
                ('field_changes', models.JSONField(default=dict, help_text='Specific field changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('additional_context', models.JSONField(default=dict, help_text='Extra context information')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ess_audit_logs', to='hrm.employeerecord')),
            ],
            options={
                'verbose_name': 'ESS Audit Log',
                'verbose_name_plural': 'ESS Audit Logs',
                'db_table': 'ess_audit_log',
            },
        ),
        migrations.CreateModel(
            name='ESSConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('configuration', models.JSONField(default=dict, help_text='Feature-specific settings')),
                ('access_roles', models.JSONField(default=list, help_text='Array of role IDs')),
                ('employee_categories', models.JSONField(default=list, help_text='Array of categories')),
                ('departments', models.JSONField(default=list, help_text='Array of department IDs')),
                ('locations', models.JSONField(default=list, help_text='Array of location IDs')),
                ('validation_rules', models.JSONField(default=dict, help_text='Field validation rules')),
                ('notification_settings', models.JSONField(default=dict, help_text='Email/SMS templates')),
                ('approval_required', models.BooleanField(default=False)),
                ('auto_approve_conditions', models.JSONField(default=dict, help_text='Auto-approval rules')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ess_configurations', to='hrm.company')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ess_config_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ESS Configuration',
                'verbose_name_plural': 'ESS Configurations',
                'db_table': 'ess_configuration',
            },
        ),
        migrations.CreateModel(
            name='ESSServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_code', models.CharField(db_index=True, max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('service_category', models.CharField(choices=[('Personal Info', 'Personal Info'), ('Benefits', 'Benefits'), ('Payroll', 'Payroll'), ('Leave', 'Leave'), ('Documents', 'Documents'), ('Training', 'Training'), ('IT Support', 'IT Support')], db_index=True, max_length=20)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('Form', 'Form'), ('Document Request', 'Document Request'), ('Information', 'Information'), ('Approval Request', 'Approval Request'), ('Automated Process', 'Automated Process')], db_index=True, max_length=20)),
                ('target_audience', models.JSONField(default=dict, help_text='Employee categories, roles, departments')),
                ('prerequisites', models.JSONField(default=dict, help_text='Required conditions')),
                ('process_steps', models.JSONField(default=list, help_text='Step-by-step process')),
                ('sla_hours', models.IntegerField(default=48)),
                ('auto_approve', models.BooleanField(default=False)),
                ('fee_applicable', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ess_services', to='hrm.company')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ess_services_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ESS Service Catalog',
                'verbose_name_plural': 'ESS Service Catalog',
                'db_table': 'ess_service_catalog',
            },
        ),
        migrations.CreateModel(
            name='ESSServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('request_data', models.JSONField(default=dict, help_text='Form data and attachments')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Pending Info', 'Pending Info'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], db_index=True, default='Medium', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('employee_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('employee_feedback', models.TextField(blank=True, null=True)),
                ('processing_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='hrm.employeerecord')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hrm.essservicecatalog')),
            ],
            options={
                'verbose_name': 'ESS Service Request',
                'verbose_name_plural': 'ESS Service Requests',
                'db_table': 'ess_service_request',
            },
        ),
        migrations.CreateModel(
            name='ESSAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('action_type', models.CharField(choices=[('Login', 'Login'), ('View Service', 'View Service'), ('Submit Request', 'Submit Request'), ('Update Profile', 'Update Profile'), ('Download Document', 'Download Document'), ('Track Request', 'Track Request')], db_index=True, max_length=20)),
                ('service_category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile'), ('Tablet', 'Tablet')], db_index=True, max_length=20, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('success_flag', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ess_analytics', to='hrm.employeerecord')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='hrm.essservicecatalog')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='hrm.essservicerequest')),
            ],
            options={
                'verbose_name': 'ESS Analytics',
                'verbose_name_plural': 'ESS Analytics',
                'db_table': 'ess_analytics',
            },
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['company', 'request_type'], name='idx_ess_matrix_company_request'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['employee_category'], name='idx_ess_matrix_category'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['department'], name='idx_ess_matrix_department'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['location'], name='idx_ess_matrix_location'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['approval_level'], name='idx_ess_matrix_level'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['approver_type'], name='idx_ess_matrix_approver_type'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['approver'], name='idx_ess_matrix_approver'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['is_active'], name='idx_ess_matrix_active'),
        ),
        migrations.AddIndex(
            model_name='employeechangerequest',
            index=models.Index(fields=['company_code', 'employee'], name='idx_ess_change_comp_emp'),
        ),
        migrations.AddIndex(
            model_name='employeechangerequest',
            index=models.Index(fields=['request_type'], name='idx_ess_change_req_type'),
        ),
        migrations.AddIndex(
            model_name='employeechangerequest',
            index=models.Index(fields=['status'], name='idx_ess_change_status'),
        ),
        migrations.AddIndex(
            model_name='employeechangerequest',
            index=models.Index(fields=['priority'], name='idx_ess_change_priority'),
        ),
        migrations.AddIndex(
            model_name='employeechangerequest',
            index=models.Index(fields=['submitted_at'], name='idx_ess_change_submitted'),
        ),
        migrations.AddIndex(
            model_name='employeechangerequest',
            index=models.Index(fields=['approved_by_user'], name='idx_ess_change_approver'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['request', 'matrix'], name='idx_ess_workflow_req_matrix'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['approver'], name='idx_ess_workflow_approver'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['approval_level'], name='idx_ess_workflow_level'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['status'], name='idx_ess_workflow_status'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['decision'], name='idx_ess_workflow_decision'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['due_date'], name='idx_ess_workflow_due'),
        ),
        migrations.AddIndex(
            model_name='essauditlog',
            index=models.Index(fields=['company_code', 'employee'], name='idx_ess_audit_company_employee'),
        ),
        migrations.AddIndex(
            model_name='essauditlog',
            index=models.Index(fields=['action'], name='idx_ess_audit_action'),
        ),
        migrations.AddIndex(
            model_name='essauditlog',
            index=models.Index(fields=['entity_type'], name='idx_ess_audit_entity_type'),
        ),
        migrations.AddIndex(
            model_name='essauditlog',
            index=models.Index(fields=['entity_id'], name='idx_ess_audit_entity_id'),
        ),
        migrations.AddIndex(
            model_name='essauditlog',
            index=models.Index(fields=['timestamp'], name='idx_ess_audit_timestamp'),
        ),
        migrations.AddIndex(
            model_name='essconfiguration',
            index=models.Index(fields=['company', 'module_name'], name='idx_ess_config_company_module'),
        ),
        migrations.AddIndex(
            model_name='essconfiguration',
            index=models.Index(fields=['feature_name'], name='idx_ess_config_feature'),
        ),
        migrations.AddIndex(
            model_name='essconfiguration',
            index=models.Index(fields=['is_enabled'], name='idx_ess_config_enabled'),
        ),
        migrations.AlterUniqueTogether(
            name='essconfiguration',
            unique_together={('company', 'module_name', 'feature_name')},
        ),
        migrations.AddIndex(
            model_name='essservicecatalog',
            index=models.Index(fields=['company', 'service_code'], name='idx_ess_service_company_code'),
        ),
        migrations.AddIndex(
            model_name='essservicecatalog',
            index=models.Index(fields=['service_category'], name='idx_ess_service_category'),
        ),
        migrations.AddIndex(
            model_name='essservicecatalog',
            index=models.Index(fields=['service_type'], name='idx_ess_service_type'),
        ),
        migrations.AddIndex(
            model_name='essservicecatalog',
            index=models.Index(fields=['is_active'], name='idx_ess_service_active'),
        ),
        migrations.AddIndex(
            model_name='essservicecatalog',
            index=models.Index(fields=['display_order'], name='idx_ess_service_order'),
        ),
        migrations.AlterUniqueTogether(
            name='essservicecatalog',
            unique_together={('company', 'service_code')},
        ),
        migrations.AddIndex(
            model_name='essservicerequest',
            index=models.Index(fields=['employee', 'service'], name='idx_ess_req_employee_service'),
        ),
        migrations.AddIndex(
            model_name='essservicerequest',
            index=models.Index(fields=['status'], name='idx_ess_req_status'),
        ),
        migrations.AddIndex(
            model_name='essservicerequest',
            index=models.Index(fields=['priority'], name='idx_ess_req_priority'),
        ),
        migrations.AddIndex(
            model_name='essservicerequest',
            index=models.Index(fields=['assigned_to_user'], name='idx_ess_req_assigned'),
        ),
        migrations.AddIndex(
            model_name='essservicerequest',
            index=models.Index(fields=['submitted_at'], name='idx_ess_req_submitted'),
        ),
        migrations.AddIndex(
            model_name='essservicerequest',
            index=models.Index(fields=['due_date'], name='idx_ess_req_due'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['company_code', 'employee'], name='idx_ess_analytics_comp_emp'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['action_type'], name='idx_ess_analytics_action'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['service_category'], name='idx_ess_analytics_category'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['service'], name='idx_ess_analytics_service'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['service_request'], name='idx_ess_analytics_request'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['action_timestamp'], name='idx_ess_analytics_timestamp'),
        ),
        migrations.AddIndex(
            model_name='essanalytics',
            index=models.Index(fields=['device_type'], name='idx_ess_analytics_device'),
        ),
    ]
