# Generated by Django 5.1.2 on 2026-01-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_approvalmatrix_employeechangerequest_and_more'),
    ]

    operations = [
    ]
