# Generated by Django 5.2.9 on 2026-01-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0005_alter_userpermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleToolbarPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Role Toolbar Permission',
                'verbose_name_plural': 'Role Toolbar Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.rolepermission',),
        ),
        migrations.CreateModel(
            name='ToolbarControlProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Master Toolbar',
                'verbose_name_plural': 'Master Toolbars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.erptoolbarcontrol',),
        ),
        migrations.CreateModel(
            name='ToolbarItemProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.erpmenuitem',),
        ),
        migrations.CreateModel(
            name='UserToolbarPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User Toolbar Permission',
                'verbose_name_plural': 'User Toolbar Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.userpermission',),
        ),
    ]




