# Generated by Django 5.2.9 on 2026-01-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolbaritemproxy',
            options={'verbose_name': 'Toolbar Registry Item', 'verbose_name_plural': 'Toolbar Registry'},
        ),
    ]




