# Generated by Django 5.2.9 on 2026-01-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar_control', '0002_alter_toolbaritemproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolbaritemproxy',
            options={'verbose_name': 'ERP Menu Item', 'verbose_name_plural': 'ERP Menu Items'},
        ),
    ]




