# Generated by Django 5.2.9 on 2026-01-04 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_entities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uom_code', models.CharField(max_length=20)),
                ('uom_name', models.CharField(max_length=100)),
                ('uom_type', models.CharField(choices=[('STOCK', 'Stock'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('GENERIC', 'Generic')], max_length=20)),
                ('decimal_allowed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_uoms', to='business_entities.company')),
            ],
            options={
                'db_table': 'common_unit_of_measure',
                'ordering': ['uom_code'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(choices=[('STOCKED', 'Stocked'), ('SERVICE', 'Service'), ('KIT', 'Kit'), ('ASSET', 'Asset')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('DISCONTINUED', 'Discontinued')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_items', to='business_entities.company')),
                ('stock_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_as_stock_uom', to='domain.unitofmeasure')),
            ],
            options={
                'db_table': 'common_item_master',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_customers', to='business_entities.company')),
            ],
            options={
                'db_table': 'common_customer',
                'ordering': ['customer_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'customer_code'), name='uq_common_customer_company_code')],
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(max_length=80)),
                ('variant_name', models.CharField(max_length=200)),
                ('is_default_variant', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='domain.itemmaster')),
            ],
            options={
                'db_table': 'common_item_variant',
                'ordering': ['sku_code'],
                'constraints': [models.UniqueConstraint(fields=('item', 'sku_code'), name='uq_common_item_variant_sku')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_suppliers', to='business_entities.company')),
            ],
            options={
                'db_table': 'common_supplier',
                'ordering': ['supplier_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'supplier_code'), name='uq_common_supplier_company_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('company', 'uom_code'), name='uq_common_uom_company_code'),
        ),
        migrations.AddConstraint(
            model_name='itemmaster',
            constraint=models.UniqueConstraint(fields=('company', 'item_code'), name='uq_common_item_company_code'),
        ),
    ]




