# Generated by Django 5.2.9 on 2026-01-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entities', '0002_initial'),
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auto_accept_ic_so',
            field=models.BooleanField(default=False, help_text='Auto-confirm IC Sales Orders to this entity'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_ic_price_list_id',
            field=models.UUIDField(blank=True, help_text='Transfer price list reference', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_tax_profile_id',
            field=models.UUIDField(blank=True, help_text='Intercompany tax behavior', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_intercompany_customer',
            field=models.BooleanField(default=False, help_text='True if this customer is a group company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='linked_company_id',
            field=models.ForeignKey(blank=True, help_text='Which company this customer represents (for IC transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_intercompany_customer', to='business_entities.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_accept_ic_po',
            field=models.BooleanField(default=False, help_text='Auto-approve incoming IC Purchase Orders'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_ic_price_list_id',
            field=models.UUIDField(blank=True, help_text='Transfer price reference', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_tax_profile_id',
            field=models.UUIDField(blank=True, help_text='Intercompany tax behavior', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_intercompany_supplier',
            field=models.BooleanField(default=False, help_text='True if this supplier is a group company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='linked_company_id',
            field=models.ForeignKey(blank=True, help_text='Which company this supplier represents (for IC transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_intercompany_supplier', to='business_entities.company'),
        ),
    ]
