# Generated by Django 5.2.9 on 2025-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReadiness',
            fields=[
                ('app_id', models.CharField(max_length=50)),
                ('module_id', models.CharField(max_length=50)),
                ('sub_module_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('menu_label', models.CharField(max_length=100)),
                ('ui_status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('N/A', 'N/A')], default='Pending', max_length=20)),
                ('dit_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('uat_status', models.CharField(choices=[('Not Started', 'Not Started'), ('InProgress', 'In Progress'), ('Complete', 'Complete')], default='Not Started', max_length=20)),
                ('script_path', models.CharField(blank=True, max_length=255, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]




