# Generated by Django 5.2.9 on 2025-12-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreadiness',
            name='bbp_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]




