# Generated by Django 5.2.9 on 2025-12-24 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_entity_type', models.CharField(choices=[('SOLE_PROP', 'Sole Proprietor'), ('PARTNERSHIP', 'Partnership'), ('PRIVATE_LTD', 'Private Limited'), ('PUBLIC_LTD', 'Public Limited'), ('LLP', 'LLP'), ('NONPROFIT', 'Non Profit / NGO'), ('GOV', 'Government'), ('OTHER', 'Other')], max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('default_currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('address_country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'be_company',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_card_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('points_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_points_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=20)),
                ('tier_qualifying_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount spent for tier qualification', max_digits=12)),
                ('enrolled_date', models.DateField(default=django.utils.timezone.now)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Loyalty',
                'verbose_name_plural': 'Customer Loyalty',
                'db_table': 'be_customer_loyalty',
                'ordering': ['-points_balance'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=20)),
                ('program_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('points_per_currency', models.DecimalField(decimal_places=2, help_text='Points earned per ₹100 spent', max_digits=5)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('redemption_rate', models.DecimalField(decimal_places=2, help_text='₹ value per point', max_digits=5)),
                ('min_points_for_redemption', models.IntegerField(default=100)),
                ('max_redemption_percent', models.DecimalField(decimal_places=2, default=100, help_text='Max % of transaction that can be paid with points', max_digits=5)),
                ('has_tiers', models.BooleanField(default=False)),
                ('tier_config', models.JSONField(blank=True, help_text='Tier thresholds and benefits', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('points_expiry_months', models.IntegerField(blank=True, help_text='Points expire after X months', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
                'db_table': 'be_loyalty_program',
                'ordering': ['program_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=20)),
                ('payment_name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card (Credit/Debit)'), ('UPI', 'UPI'), ('WALLET', 'Digital Wallet'), ('BANK_TRANSFER', 'Bank Transfer'), ('GIFT_CARD', 'Gift Card/Voucher'), ('CREDIT', 'Credit/Account')], max_length=20)),
                ('is_pos_enabled', models.BooleanField(default=True, help_text='Available in POS')),
                ('requires_approval', models.BooleanField(default=False)),
                ('open_cash_drawer', models.BooleanField(default=False, help_text='Open cash drawer when selected')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gl_account', models.CharField(blank=True, help_text='General Ledger account code', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier for UI', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'be_payment_method',
                'ordering': ['display_order', 'payment_name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=20)),
                ('promotion_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_AMOUNT', 'Fixed Amount Off'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('BUNDLE', 'Bundle Discount'), ('QUANTITY_BASED', 'Quantity Based')], max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='For percentage discounts', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='For fixed amount discounts', max_digits=12)),
                ('buy_quantity', models.IntegerField(blank=True, help_text='Buy this many', null=True)),
                ('get_quantity', models.IntegerField(blank=True, help_text='Get this many free/discounted', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('applies_to_all_items', models.BooleanField(default=False)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('max_uses_total', models.IntegerField(blank=True, help_text='Total times this can be used', null=True)),
                ('max_uses_per_customer', models.IntegerField(blank=True, null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('is_pos_enabled', models.BooleanField(default=True)),
                ('is_online_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority promotions apply first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'be_promotion',
                'ordering': ['-priority', 'promotion_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxClassEnhanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(max_length=20)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('GST', 'GST (India)'), ('VAT', 'VAT'), ('SALES_TAX', 'Sales Tax'), ('EXEMPT', 'Tax Exempt')], default='GST', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Total tax rate (e.g., 18.00 for 18%)', max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Central GST rate', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='State GST rate', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Integrated GST rate', max_digits=5)),
                ('tax_gl_account', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Class (Enhanced)',
                'verbose_name_plural': 'Tax Classes (Enhanced)',
                'db_table': 'be_tax_class_enhanced',
                'ordering': ['tax_rate', 'tax_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default discount for this group', max_digits=5)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, Net 45', max_length=50, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_groups', to='business_entities.company')),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'db_table': 'be_customer_group',
                'ordering': ['group_name'],
            },
        ),
    ]




