# Generated by Django 5.2.9 on 2025-12-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_entities', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='default_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.pricelist'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='company.operationalcustomer'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_programs', to='business_entities.company'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='business_entities.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='business_entities.company'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to_categories',
            field=models.ManyToManyField(blank=True, to='company.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to_items',
            field=models.ManyToManyField(blank=True, to='company.itemmaster'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='business_entities.company'),
        ),
        migrations.AddField(
            model_name='taxclassenhanced',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_classes_enhanced', to='business_entities.company'),
        ),
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together={('company', 'group_code')},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltyprogram',
            unique_together={('company', 'program_code')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('company', 'payment_code')},
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('company', 'promotion_code')},
        ),
        migrations.AlterUniqueTogether(
            name='taxclassenhanced',
            unique_together={('company', 'tax_code')},
        ),
    ]




