# Generated by Django 5.1.2 on 2026-01-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entities', '0002_initial'),
        ('company', '0003_remove_location_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CustomerLoyalty',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='company.operationalcustomer'),
        ),
    ]
